### ISSUE TITLE
can't make extended_qm9_.pt by running "python3 extend_pyg.py ./data qm9_motifs_100.pt 32"

### ISSUE THREAD

**Issue by Neo-Flash** [yifeiwang15/MotifConv#1]
Hi!
Thank you for sharing your excellent work here !
I can't make extended_qm9_.pt by running "python3 extend_pyg.py ./data qm9_motifs_100.pt 32"
could you  please provide  extended_qm9_.pt?

thanks :)

**Comment by yifeiwang15** [comment]
I understand that running the 'extend_pyg.py' file can be challenging when users have different environments for CUDA compilation. I executed the 'extend_pyg.py' file using 8 V100 GPUs, with the following configuration details:

NVIDIA-SMI version: 515.65.01
Driver version: 515.65.01
CUDA version: 11.7

I have created a shared Google file containing the preprocessed 'extend_qm9.pt' data for your reference. You can access it through the following link: https://drive.google.com/file/d/1I2mbs8P-_WAhAyKbVwEzds9fG0Lxk8Sx/view?usp=sharing

**Comment by Neo-Flash** [comment]
Thank you for your prompt response and for sharing the 'extend_qm9.pt' data！Your help has been invaluable in my project. As a beginner in AI and graph neural networks, your work has been a great resource. Wishing you all the best in your future endeavors：）
